version: '3'

services:
  my-awesome-app:
    build: .
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/app
    depends_on:
      - my-awesome-db

  my-awesome-db:
    image: mariadb:10.3
    command:  "--character-set-server=utf8 --collation-server=utf8_general_ci --innodb-use-native-aio=0"
    restart: "no"
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: my_awesome_db
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_ROOT_HOST: "%"

  my-awesome-adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8080:8080
    depends_on:
      - my-awesome-db
